### ISSUE TITLE
apiRoot restrictions

### ISSUE THREAD

**Issue by puzzle-it-nu** [technowledgy/vue-postgrest#21]
I would like to open up a legacy database using postgrest and this project but my api server is not the same machine where the client is running.
Reading the docs it seems that apiRoot is an URI and that I could use http://api-server:4000 but that is not the case because in Query.js line 26 you call super with the optional argument of the href of the browser and as url the apiRoot and that returns something rather interesting but not what I expected.
apiRoot smahed together with my brower URL :-(

A simple solution woulld be to check if apiRoot is a absolute URI or a relative URI and call super in accordingly with one or two arguments.

Regards.

Joop

**Comment by wolfgangwalther** [comment]
Thanks for the report. I agree, absolute apiRoot should work as well.

The problem was not the call to super(), but the regex in the replace before that. Replacing `//` with `/` doesn't go well with absolute URL's like `http://...`..

**Comment by puzzle-it-nu** [comment]
Thanks
